# Generated by Django 3.1 on 2021-05-07 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cartitem',
            new_name='Cart_items',
        ),
    ]
